import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#006e0c',
        'on-secondary-fixed': '#001d34',
        'on-primary-fixed': '#002201',
        'surface-container-highest': '#e3e2e0',
        'tertiary-container': '#bc5540',
        'secondary-fixed-dim': '#9acbff',
        secondary: '#00629e',
        tertiary: '#9c3e2b',
        'surface-dim': '#dbdad7',
        'on-tertiary-fixed-variant': '#802918',
        'on-primary-fixed-variant': '#005307',
        'on-primary-container': '#f8fff0',
        'surface-container': '#efeeeb',
        'on-error-container': '#93000a',
        'secondary-container': '#61b4fe',
        primary: '#006c0c',
        'on-tertiary-fixed': '#3e0500',
        'inverse-surface': '#2f312f',
        'on-secondary-container': '#004470',
        'outline-variant': '#becab7',
        'on-secondary-fixed-variant': '#004a79',
        error: '#ba1a1a',
        'surface-variant': '#e3e2e0',
        'primary-fixed': '#92fa83',
        'on-surface-variant': '#3f4a3b',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        background: '#faf9f6',
        surface: '#faf9f6',
        'on-error': '#ffffff',
        'surface-bright': '#faf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'on-background': '#1a1c1a',
        'surface-container-high': '#e9e8e5',
        'tertiary-fixed-dim': '#ffb4a5',
        'inverse-on-surface': '#f2f1ee',
        'error-container': '#ffdad6',
        'primary-container': '#1c871e',
        outline: '#6f7a6a',
        'on-tertiary': '#ffffff',
        'on-surface': '#1a1c1a',
        'inverse-primary': '#77dd6a',
        'secondary-fixed': '#cfe5ff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#ffdad3',
        'primary-fixed-dim': '#77dd6a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-margin-desktop': '64px',
        'container-margin-mobile': '20px',
        gutter: '16px',
        base: '8px',
        'section-gap': '80px',
      },
      fontFamily: {
        sans: ['Atkinson Hyperlegible Next', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      animation: {
        'ping-slow': 'ping 3s cubic-bezier(0, 0, 0.2, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { transform: 'translateY(16px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
      },
    },
  },
  plugins: [],
}

export default config