export const COPY = {
  common: {
    appName: 'Climate Commons',
    loading: 'Loading...',
    error: 'Something went wrong. Please try again.',
    saveButton: 'Save',
    cancelButton: 'Cancel',
    deleteButton: 'Delete',
    confirmButton: 'Confirm',
    backButton: 'Back',
  },
  nav: {
    home: 'Home',
    research: 'Research',
    forum: 'Forum',
    actions: 'Actions',
    policy: 'Policy',
    admin: 'Admin',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
  },
  auth: {
    loginTitle: 'Log in',
    signupTitle: 'Sign up',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    submitButton: 'Submit',
    loginButton: 'Log in',
    signupButton: 'Sign up',
    logoutSuccess: 'You have been logged out.',
    invalidCredentials: 'Invalid email or password.',
  },
  bookmarks: {
    title: 'Bookmarks',
    noBookmarks: 'No bookmarks yet.',
  },
  research: {
    title: 'Research',
    submitPaper: 'Submit Paper',
    browsePapers: 'Browse Papers',
    paperTitleLabel: 'Paper Title',
    authorsLabel: 'Authors',
    abstractLabel: 'Abstract',
    proposeTitle: 'Propose Research',
    categoryLabel: 'Category',
  },
  forum: {
    title: 'Forum',
    newTopic: 'New Topic',
    replyButton: 'Reply',
    latestPosts: 'Latest Posts',
    noTopics: 'No topics yet. Be the first to start a discussion!',
    topicTitleLabel: 'Topic Title',
    bodyLabel: 'Body',
    categoryLabel: 'Category',
  },
  actions: {
    title: 'Actions',
    proposeAction: 'Propose Action',
    joinAction: 'Join Action',
    actionTitleLabel: 'Action Title',
    descriptionLabel: 'Description',
    locationLabel: 'Location',
    dateLabel: 'Date',
    submitButton: 'Submit',
  },
  policy: {
    title: 'Policy',
    viewProposals: 'View Proposals',
    submitProposal: 'Submit Proposal',
    proposalTitleLabel: 'Proposal Title',
    summaryLabel: 'Summary',
  },
  admin: {
    title: 'Admin',
    users: 'Users',
    moderation: 'Moderation',
    analytics: 'Analytics',
    inviteUser: 'Invite User',
    banUser: 'Ban User',
  },
  profile: {
    title: 'Profile',
    contributions: 'Contributions',
    verifiedIdeas: 'Verified Ideas',
    editTitle: 'Edit Profile',
  },
  notifications: {
    title: 'Notifications',
    markAsRead: 'Mark as read',
    noNotifications: 'No notifications yet.',
  },
  settings: {
    title: 'Account Settings',
    emailLabel: 'Email',
    displayNameLabel: 'Display Name',
    bioLabel: 'Bio',
  },
} as const
