/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as PolicyIndexRouteImport } from './routes/policy/index'
import { Route as PartnershipsIndexRouteImport } from './routes/partnerships/index'
import { Route as OpenDataIndexRouteImport } from './routes/open-data/index'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as ForumGuidelinesIndexRouteImport } from './routes/forum-guidelines/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ActionsIndexRouteImport } from './routes/actions/index'
import { Route as ResearchProposeRouteImport } from './routes/research/propose'
import { Route as ResearchIdRouteImport } from './routes/research/$id'
import { Route as ProfileChar91idChar93RouteImport } from './routes/profile/[id]'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as PolicyIdRouteImport } from './routes/policy/$id'
import { Route as ForumNewRouteImport } from './routes/forum/new'
import { Route as ForumIdRouteImport } from './routes/forum/$id'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProposalsRouteImport } from './routes/admin/proposals'
import { Route as AdminPolicyRouteImport } from './routes/admin/policy'
import { Route as AdminPartnershipsRouteImport } from './routes/admin/partnerships'
import { Route as AdminFlagsRouteImport } from './routes/admin/flags'
import { Route as AdminDatasetsRouteImport } from './routes/admin/datasets'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminClaimsRouteImport } from './routes/admin/claims'
import { Route as AdminActionsRouteImport } from './routes/admin/actions'
import { Route as ActionsRegisterRouteImport } from './routes/actions/register'
import { Route as ActionsIdRouteImport } from './routes/actions/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyIndexRoute = PolicyIndexRouteImport.update({
  id: '/policy/',
  path: '/policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsIndexRoute = PartnershipsIndexRouteImport.update({
  id: '/partnerships/',
  path: '/partnerships/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenDataIndexRoute = OpenDataIndexRouteImport.update({
  id: '/open-data/',
  path: '/open-data/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumGuidelinesIndexRoute = ForumGuidelinesIndexRouteImport.update({
  id: '/forum-guidelines/',
  path: '/forum-guidelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ActionsIndexRoute = ActionsIndexRouteImport.update({
  id: '/actions/',
  path: '/actions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProposeRoute = ResearchProposeRouteImport.update({
  id: '/research/propose',
  path: '/research/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChar91idChar93Route = ProfileChar91idChar93RouteImport.update({
  id: '/profile/id',
  path: '/profile/id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyIdRoute = PolicyIdRouteImport.update({
  id: '/policy/$id',
  path: '/policy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNewRoute = ForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/forum/$id',
  path: '/forum/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProposalsRoute = AdminProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPolicyRoute = AdminPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnershipsRoute = AdminPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatasetsRoute = AdminDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRoute,
} as any)
const ActionsRegisterRoute = ActionsRegisterRouteImport.update({
  id: '/actions/register',
  path: '/actions/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsIdRoute = ActionsIdRouteImport.update({
  id: '/actions/$id',
  path: '/actions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/actions/$id': typeof ActionsIdRoute
  '/actions/register': typeof ActionsRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/policy/$id': typeof PolicyIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/id': typeof ProfileChar91idChar93Route
  '/research/$id': typeof ResearchIdRoute
  '/research/propose': typeof ResearchProposeRoute
  '/actions/': typeof ActionsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/forum-guidelines/': typeof ForumGuidelinesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/open-data/': typeof OpenDataIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/actions/$id': typeof ActionsIdRoute
  '/actions/register': typeof ActionsRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/policy/$id': typeof PolicyIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/id': typeof ProfileChar91idChar93Route
  '/research/$id': typeof ResearchIdRoute
  '/research/propose': typeof ResearchProposeRoute
  '/actions': typeof ActionsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/forum-guidelines': typeof ForumGuidelinesIndexRoute
  '/forum': typeof ForumIndexRoute
  '/open-data': typeof OpenDataIndexRoute
  '/partnerships': typeof PartnershipsIndexRoute
  '/policy': typeof PolicyIndexRoute
  '/research': typeof ResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/actions/$id': typeof ActionsIdRoute
  '/actions/register': typeof ActionsRegisterRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/partnerships': typeof AdminPartnershipsRoute
  '/admin/policy': typeof AdminPolicyRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/forum/$id': typeof ForumIdRoute
  '/forum/new': typeof ForumNewRoute
  '/policy/$id': typeof PolicyIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/id': typeof ProfileChar91idChar93Route
  '/research/$id': typeof ResearchIdRoute
  '/research/propose': typeof ResearchProposeRoute
  '/actions/': typeof ActionsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/forum-guidelines/': typeof ForumGuidelinesIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/open-data/': typeof OpenDataIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/policy/': typeof PolicyIndexRoute
  '/research/': typeof ResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/notifications'
    | '/settings'
    | '/actions/$id'
    | '/actions/register'
    | '/admin/actions'
    | '/admin/claims'
    | '/admin/contact'
    | '/admin/datasets'
    | '/admin/flags'
    | '/admin/partnerships'
    | '/admin/policy'
    | '/admin/proposals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$id'
    | '/forum/new'
    | '/policy/$id'
    | '/profile/$id'
    | '/profile/id'
    | '/research/$id'
    | '/research/propose'
    | '/actions/'
    | '/admin/'
    | '/contact/'
    | '/forum-guidelines/'
    | '/forum/'
    | '/open-data/'
    | '/partnerships/'
    | '/policy/'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/notifications'
    | '/settings'
    | '/actions/$id'
    | '/actions/register'
    | '/admin/actions'
    | '/admin/claims'
    | '/admin/contact'
    | '/admin/datasets'
    | '/admin/flags'
    | '/admin/partnerships'
    | '/admin/policy'
    | '/admin/proposals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$id'
    | '/forum/new'
    | '/policy/$id'
    | '/profile/$id'
    | '/profile/id'
    | '/research/$id'
    | '/research/propose'
    | '/actions'
    | '/admin'
    | '/contact'
    | '/forum-guidelines'
    | '/forum'
    | '/open-data'
    | '/partnerships'
    | '/policy'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookmarks'
    | '/notifications'
    | '/settings'
    | '/actions/$id'
    | '/actions/register'
    | '/admin/actions'
    | '/admin/claims'
    | '/admin/contact'
    | '/admin/datasets'
    | '/admin/flags'
    | '/admin/partnerships'
    | '/admin/policy'
    | '/admin/proposals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/login'
    | '/auth/signup'
    | '/forum/$id'
    | '/forum/new'
    | '/policy/$id'
    | '/profile/$id'
    | '/profile/id'
    | '/research/$id'
    | '/research/propose'
    | '/actions/'
    | '/admin/'
    | '/contact/'
    | '/forum-guidelines/'
    | '/forum/'
    | '/open-data/'
    | '/partnerships/'
    | '/policy/'
    | '/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  ActionsIdRoute: typeof ActionsIdRoute
  ActionsRegisterRoute: typeof ActionsRegisterRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ForumIdRoute: typeof ForumIdRoute
  ForumNewRoute: typeof ForumNewRoute
  PolicyIdRoute: typeof PolicyIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileChar91idChar93Route: typeof ProfileChar91idChar93Route
  ResearchIdRoute: typeof ResearchIdRoute
  ResearchProposeRoute: typeof ResearchProposeRoute
  ActionsIndexRoute: typeof ActionsIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ForumGuidelinesIndexRoute: typeof ForumGuidelinesIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  OpenDataIndexRoute: typeof OpenDataIndexRoute
  PartnershipsIndexRoute: typeof PartnershipsIndexRoute
  PolicyIndexRoute: typeof PolicyIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/': {
      id: '/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof PolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships/': {
      id: '/partnerships/'
      path: '/partnerships'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-data/': {
      id: '/open-data/'
      path: '/open-data'
      fullPath: '/open-data/'
      preLoaderRoute: typeof OpenDataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum-guidelines/': {
      id: '/forum-guidelines/'
      path: '/forum-guidelines'
      fullPath: '/forum-guidelines/'
      preLoaderRoute: typeof ForumGuidelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/actions/': {
      id: '/actions/'
      path: '/actions'
      fullPath: '/actions/'
      preLoaderRoute: typeof ActionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/propose': {
      id: '/research/propose'
      path: '/research/propose'
      fullPath: '/research/propose'
      preLoaderRoute: typeof ResearchProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/id': {
      id: '/profile/id'
      path: '/profile/id'
      fullPath: '/profile/id'
      preLoaderRoute: typeof ProfileChar91idChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/$id': {
      id: '/policy/$id'
      path: '/policy/$id'
      fullPath: '/policy/$id'
      preLoaderRoute: typeof PolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/new': {
      id: '/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof ForumNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/forum/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proposals': {
      id: '/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AdminProposalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policy': {
      id: '/admin/policy'
      path: '/policy'
      fullPath: '/admin/policy'
      preLoaderRoute: typeof AdminPolicyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partnerships': {
      id: '/admin/partnerships'
      path: '/partnerships'
      fullPath: '/admin/partnerships'
      preLoaderRoute: typeof AdminPartnershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/datasets': {
      id: '/admin/datasets'
      path: '/datasets'
      fullPath: '/admin/datasets'
      preLoaderRoute: typeof AdminDatasetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/actions/register': {
      id: '/actions/register'
      path: '/actions/register'
      fullPath: '/actions/register'
      preLoaderRoute: typeof ActionsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/$id': {
      id: '/actions/$id'
      path: '/actions/$id'
      fullPath: '/actions/$id'
      preLoaderRoute: typeof ActionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminDatasetsRoute: typeof AdminDatasetsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminPartnershipsRoute: typeof AdminPartnershipsRoute
  AdminPolicyRoute: typeof AdminPolicyRoute
  AdminProposalsRoute: typeof AdminProposalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminContactRoute: AdminContactRoute,
  AdminDatasetsRoute: AdminDatasetsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminPartnershipsRoute: AdminPartnershipsRoute,
  AdminPolicyRoute: AdminPolicyRoute,
  AdminProposalsRoute: AdminProposalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  ActionsIdRoute: ActionsIdRoute,
  ActionsRegisterRoute: ActionsRegisterRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ForumIdRoute: ForumIdRoute,
  ForumNewRoute: ForumNewRoute,
  PolicyIdRoute: PolicyIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileChar91idChar93Route: ProfileChar91idChar93Route,
  ResearchIdRoute: ResearchIdRoute,
  ResearchProposeRoute: ResearchProposeRoute,
  ActionsIndexRoute: ActionsIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ForumGuidelinesIndexRoute: ForumGuidelinesIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  OpenDataIndexRoute: OpenDataIndexRoute,
  PartnershipsIndexRoute: PartnershipsIndexRoute,
  PolicyIndexRoute: PolicyIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './app.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
